Repository apache/cloudberry, pull requests merged in 2024-08, with the labels that each got.

#556 Update the image to Rockylinux8 to ensure the normal operation of CI
  .github/workflows/build.yml
  .github/workflows/build_external_fts.yml
  .github/workflows/release.yml
  concourse/scripts/compile_gpdb.bash
Labels: CI

#541 Use syscache lookup in ShouldUseReservedSegno
  src/backend/access/appendonly/appendonlywriter.c
Labels: cherry-pick

#562 Fix: Add ao_unique_index_build test in greenplum_schedule
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/test/isolation2/input/uao/index_build_reltuples.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/index_build_reltuples.source
  src/test/regress/greenplum_schedule
Labels: cherry-pick

#574 Doc: update the alter table help command content
  doc/src/sgml/ref/alter_table.sgml
Labels: type: Documentation
